
import { BaseCharacterFirestore } from "../types/character";

export const characterData: BaseCharacterFirestore[] = [
    {
        name: 'Kumo',
        defaultAnimation: '',
        animation: 'characters/kumo_1.mp4',
        transformThresholds: [7, 12, 20, 31, 42, 70],
        transformTempAnimations: [
            'characters/kumo_transform_temp_1.mp4',
            'characters/kumo_transform_temp_2.mp4',
            'characters/kumo_transform_temp_3.mp4',
            'characters/kumo_transform_temp_4.mp4',
            'characters/kumo_transform_temp_5.mp4',
            'characters/kumo_transform_temp_6.mp4',
        ],
        transformAnimations: [
            'characters/kumo_2.mp4',
            'characters/kumo_3.mp4',
            'characters/kumo_4.mp4',
            'characters/kumo_5.mp4',
            'characters/kumo_6.mp4',
            'characters/kumo_7.mp4',
        ],
        actionAnimations: [
            'characters/kumo/action/kumo_action_1.mp4',
            'characters/kumo/action/kumo_action_2.mp4',
            'characters/kumo/action/kumo_action_3.mp4',
            'characters/kumo/action/kumo_action_4.mp4',
            'characters/kumo/action/kumo_action_5.mp4',
            'characters/kumo/action/kumo_action_6.mp4',
            'characters/kumo/action/kumo_action_7.mp4',
        ],
        damageAnimations: [
            'characters/kumo/damage/kumo_damage_1.mp4',
            'characters/kumo/damage/kumo_damage_2.mp4',
            'characters/kumo/damage/kumo_damage_3.mp4',
            'characters/kumo/damage/kumo_damage_4.mp4',
            'characters/kumo/damage/kumo_damage_5.mp4',
            'characters/kumo/damage/kumo_damage_6.mp4',
            'characters/kumo/damage/kumo_damage_7.mp4',
        ],
    },
    {
        name: 'Kiiro',
        defaultAnimation: '',
        animation: 'characters/kiiro_1.mp4',
        transformThresholds: [7, 12, 20, 31, 42, 70],
        transformTempAnimations: [
            'characters/kiiro_transform_temp_1.mp4',
            'characters/kiiro_transform_temp_2.mp4',
            'characters/kiiro_transform_temp_3.mp4',
            'characters/kiiro_transform_temp_4.mp4',
            'characters/kiiro_transform_temp_5.mp4',
            'characters/kiiro_transform_temp_6.mp4',
        ],
        transformAnimations: [
            'characters/kiiro_2.mp4',
            'characters/kiiro_3.mp4',
            'characters/kiiro_4.mp4',
            'characters/kiiro_5.mp4',
            'characters/kiiro_6.mp4',
            'characters/kiiro_7.mp4',
        ],
        actionAnimations: [
            'characters/kiiro/action/kiiro_action_1.mp4',
            'characters/kiiro/action/kiiro_action_2.mp4',
            'characters/kiiro/action/kiiro_action_3.mp4',
            'characters/kiiro/action/kiiro_action_4.mp4',
            'characters/kiiro/action/kiiro_action_5.mp4',
            'characters/kiiro/action/kiiro_action_6.mp4',
            'characters/kiiro/action/kiiro_action_7.mp4',
        ],
        damageAnimations: [
            'characters/kiiro/damage/kiiro_damage_1.mp4',
            'characters/kiiro/damage/kiiro_damage_2.mp4',
            'characters/kiiro/damage/kiiro_damage_3.mp4',
            'characters/kiiro/damage/kiiro_damage_4.mp4',
            'characters/kiiro/damage/kiiro_damage_5.mp4',
            'characters/kiiro/damage/kiiro_damage_6.mp4',
            'characters/kiiro/damage/kiiro_damage_7.mp4',
        ],
    },
    {
        name: 'Maguro',
        defaultAnimation: '',
        animation: 'characters/maguro_1.mp4',
        transformThresholds: [7, 12, 20, 31, 42, 70],
        transformTempAnimations: [
            'characters/maguro_transform_temp_1.mp4',
            'characters/maguro_transform_temp_2.mp4',
            'characters/maguro_transform_temp_3.mp4',
            'characters/maguro_transform_temp_4.mp4',
            'characters/maguro_transform_temp_5.mp4',
            'characters/maguro_transform_temp_6.mp4',
        ],
        transformAnimations: [
            'characters/maguro_2.mp4',
            'characters/maguro_3.mp4',
            'characters/maguro_4.mp4',
            'characters/maguro_5.mp4',
            'characters/maguro_6.mp4',
            'characters/maguro_7.mp4',
        ],
        actionAnimations: [
            'characters/maguro/action/maguro_action_1.mp4',
            'characters/maguro/action/maguro_action_2.mp4',
            'characters/maguro/action/maguro_action_3.mp4',
            'characters/maguro/action/maguro_action_4.mp4',
            'characters/maguro/action/maguro_action_5.mp4',
            'characters/maguro/action/maguro_action_6.mp4',
            'characters/maguro/action/maguro_action_7.mp4',
        ],
        damageAnimations: [
            'characters/maguro/damage/maguro_damage_1.mp4',
            'characters/maguro/damage/maguro_damage_2.mp4',
            'characters/maguro/damage/maguro_damage_3.mp4',
            'characters/maguro/damage/maguro_damage_4.mp4',
            'characters/maguro/damage/maguro_damage_5.mp4',
            'characters/maguro/damage/maguro_damage_6.mp4',
            'characters/maguro/damage/maguro_damage_7.mp4',
        ],
    },

    {
        name: 'Yumi',
        defaultAnimation: '',
        animation: 'characters/yumi_1.mp4',
        transformThresholds: [7, 12, 20, 31, 42, 70],
        transformTempAnimations: [
            'characters/yumi_transform_temp_1.mp4',
            'characters/yumi_transform_temp_2.mp4',
            'characters/yumi_transform_temp_3.mp4',
            'characters/yumi_transform_temp_4.mp4',
            'characters/yumi_transform_temp_5.mp4',
            'characters/yumi_transform_temp_6.mp4',
        ],
        transformAnimations: [
            'characters/yumi_2.mp4',
            'characters/yumi_3.mp4',
            'characters/yumi_4.mp4',
            'characters/yumi_5.mp4',
            'characters/yumi_6.mp4',
            'characters/yumi_7.mp4',
        ],
        actionAnimations: [
            'characters/yumi/action/yumi_action_1.mp4',
            'characters/yumi/action/yumi_action_2.mp4',
            'characters/yumi/action/yumi_action_3.mp4',
            'characters/yumi/action/yumi_action_4.mp4',
            'characters/yumi/action/yumi_action_5.mp4',
            'characters/yumi/action/yumi_action_6.mp4',
            'characters/yumi/action/yumi_action_7.mp4',
        ],
        damageAnimations: [
            'characters/yumi/damage/yumi_damage_1.mp4',
            'characters/yumi/damage/yumi_damage_2.mp4',
            'characters/yumi/damage/yumi_damage_3.mp4',
            'characters/yumi/damage/yumi_damage_4.mp4',
            'characters/yumi/damage/yumi_damage_5.mp4',
            'characters/yumi/damage/yumi_damage_6.mp4',
            'characters/yumi/damage/yumi_damage_7.mp4',
        ],
    },
    {
        name: 'Mushi',
        defaultAnimation: '',
        animation: 'characters/mushi_1.mp4',
        transformThresholds: [7, 12, 20, 31, 42, 70],
        transformTempAnimations: [
            'characters/mushi_transform_temp_1.mp4',
            'characters/mushi_transform_temp_2.mp4',
            'characters/mushi_transform_temp_3.mp4',
            'characters/mushi_transform_temp_4.mp4',
            'characters/mushi_transform_temp_5.mp4',
            'characters/mushi_transform_temp_6.mp4',
        ],
        transformAnimations: [
            'characters/mushi_2.mp4',
            'characters/mushi_3.mp4',
            'characters/mushi_4.mp4',
            'characters/mushi_5.mp4',
            'characters/mushi_6.mp4',
            'characters/mushi_7.mp4',
        ],
        actionAnimations: [
            'characters/mushi/action/mushi_action_1.mp4',
            'characters/mushi/action/mushi_action_2.mp4',
            'characters/mushi/action/mushi_action_3.mp4',
            'characters/mushi/action/mushi_action_4.mp4',
            'characters/mushi/action/mushi_action_5.mp4',
            'characters/mushi/action/mushi_action_6.mp4',
            'characters/mushi/action/mushi_action_7.mp4',
        ],
        damageAnimations: [
            'characters/mushi/damage/mushi_damage_1.mp4',
            'characters/mushi/damage/mushi_damage_2.mp4',
            'characters/mushi/damage/mushi_damage_3.mp4',
            'characters/mushi/damage/mushi_damage_4.mp4',
            'characters/mushi/damage/mushi_damage_5.mp4',
            'characters/mushi/damage/mushi_damage_6.mp4',
            'characters/mushi/damage/mushi_damage_7.mp4',
        ],
    },

    {
        name: 'Roku',
        defaultAnimation: '',
        animation: 'characters/roku_1.mp4',
        transformThresholds: [7, 12, 20, 31, 42, 70],
        transformTempAnimations: [
            'characters/roku_transform_temp_1.mp4',
            'characters/roku_transform_temp_2.mp4',
            'characters/roku_transform_temp_3.mp4',
            'characters/roku_transform_temp_4.mp4',
            'characters/roku_transform_temp_5.mp4',
            'characters/roku_transform_temp_6.mp4',
        ],
        transformAnimations: [
            'characters/roku_2.mp4',
            'characters/roku_3.mp4',
            'characters/roku_4.mp4',
            'characters/roku_5.mp4',
            'characters/roku_6.mp4',
            'characters/roku_7.mp4',
        ],
        actionAnimations: [
            'characters/roku/action/roku_action_1.mp4',
            'characters/roku/action/roku_action_2.mp4',
            'characters/roku/action/roku_action_3.mp4',
            'characters/roku/action/roku_action_4.mp4',
            'characters/roku/action/roku_action_5.mp4',
            'characters/roku/action/roku_action_6.mp4',
            'characters/roku/action/roku_action_7.mp4',
        ],
        damageAnimations: [
            'characters/roku/damage/roku_damage_1.mp4',
            'characters/roku/damage/roku_damage_2.mp4',
            'characters/roku/damage/roku_damage_3.mp4',
            'characters/roku/damage/roku_damage_4.mp4',
            'characters/roku/damage/roku_damage_5.mp4',
            'characters/roku/damage/roku_damage_6.mp4',
            'characters/roku/damage/roku_damage_7.mp4',
        ],
    },


];

