#!/usr/bin/env node
/**
 * seed_kanji_drop.js
 *
 * One-time script: uploads KanjiDropData (TILES, MERGES, TARGET_POOL) to
 * the Firestore document  kanjiDrop/gameData.
 *
 * Usage
 * ─────
 *   export GOOGLE_APPLICATION_CREDENTIALS=/path/to/serviceAccount.json
 *   node scripts/seed_kanji_drop.js [--dryRun]
 *
 * Install deps once if needed:
 *   npm install firebase-admin
 */

const admin = require('firebase-admin');

// ─── Parse args ──────────────────────────────────────────────────────────────
const DRY = process.argv.includes('--dryRun');
if (DRY) console.log('🔍 Dry-run mode — nothing will be written.');

// ─── Init Firebase Admin ─────────────────────────────────────────────────────
admin.initializeApp({
    credential: admin.credential.applicationDefault(),
});
const db = admin.firestore();

// ─── Static data (copy of KanjiDropData values, JS-only) ─────────────────────

const TIER_COLORS = [
    { fill: '#0ea5e9', text: '#f0f9ff', glow: '#38bdf8' },
    { fill: '#22c55e', text: '#f0fdf4', glow: '#4ade80' },
    { fill: '#f59e0b', text: '#fffbeb', glow: '#fbbf24' },
    { fill: '#d946ef', text: '#fdf4ff', glow: '#e879f9' },
    { fill: '#3b82f6', text: '#eff6ff', glow: '#60a5fa' },
    { fill: '#f97316', text: '#fff7ed', glow: '#fb923c' },
    { fill: '#8b5cf6', text: '#f5f3ff', glow: '#a78bfa' },
    { fill: '#ec4899', text: '#fdf2f8', glow: '#f472b6' },
    { fill: '#14b8a6', text: '#f0fdfa', glow: '#2dd4bf' },
    { fill: '#74faea', text: '#223531', glow: '#2dd4bf' },
    { fill: '#c9f33f', text: '#274e3c', glow: '#91fb54' },
    { fill: '#a988e1', text: '#0a3d31', glow: '#f85fdc' },
    { fill: '#eff326', text: '#68232e', glow: '#ecf935' },
    { fill: '#9d4c52', text: '#1b090c', glow: 'rgb(250, 95, 222)' },
    { fill: '#c58476', text: '#74c6e4', glow: '#ba3ffc' },
    { fill: '#fcfafb', text: '#0c0305', glow: '#fafafa' },
    { fill: '#f699a1', text: '#68232e', glow: '#f78888' },
    { fill: '#9e4149', text: '#eed9dd', glow: '#f3adad' },
    { fill: '#8790f4', text: '#fdfdfd', glow: '#f7f3f3' },
    { fill: '#99e7f6', text: '#060606', glow: '#f78888' },
    { fill: '#62b986', text: '#060606', glow: '#f78888' },
];

// Target pool — IDs of kanji the game randomly selects as the goal
const TARGET_POOL = [
    'messenger', 'work', 'onfoot', 'life', 'horizon', 'finger', 'show', 'altar', 'ten',
    'character', 'frame', 'punish', 'direction', 'wash', 'elife', 'separate', 'fruit',
    'king', 'hand', 'eye', 'heart', 'water', 'old', 'dawn', 'rest', 'meet',
    'book', 'yet', 'white', 'flame', 'bright', 'grove', 'safety', 'likeable',
    'think', 'gold', 'forest', 'morning', 'talk', 'love',
];

// Tiles — only store minimal fields (char, meaning, tier); colours computed client-side
const RAW_TILES = {
    hline: { char: '一', meaning: 'one / horizontal stroke', tier: 0 },
    vline: { char: '｜', meaning: 'vertical stroke', tier: 0 },
    dbox: { char: '冂', meaning: 'downward box', tier: 0 },
    rbend: { char: '⺄', meaning: 'bend right side', tier: 0 },
    cstroke: { char: 'ノ', meaning: 'curved left stroke', tier: 0 },
    dot: { char: '丶', meaning: 'dot stroke', tier: 0 },
    hook: { char: '亅', meaning: 'hook stroke', tier: 0 },
    bend: { char: '乙', meaning: 'bend stroke', tier: 0 },
    benthook: { char: '乚', meaning: 'bent hook', tier: 0 },
    divining: { char: '卜', meaning: 'divining/fortune telling', tier: 0 },
    cliff: { char: '厂', meaning: 'cliff', tier: 1 },
    wrap: { char: '勹', meaning: 'wrap', tier: 1 },
    person: { char: '人', meaning: 'person', tier: 1 },
    spoon: { char: '匕', meaning: 'spoon', tier: 1 },
    tperson: { char: '亻', meaning: 'person', tier: 1 },
    street: { char: '丁', meaning: 'street', tier: 1 },
    na: { char: 'ナ ', meaning: 'na radical', tier: 1 },
    cover: { char: '冖', meaning: 'cover', tier: 1 },
    container: { char: '凵', meaning: 'container', tier: 1 },
    sbox: { char: '匚', meaning: 'container', tier: 1 },
    eight: { char: 'ハ', meaning: 'eight', tier: 1 },
    lid: { char: '亠', meaning: 'lid', tier: 1 },
    grass: { char: '丷', meaning: 'grass', tier: 1 },
    two: { char: '二', meaning: 'two', tier: 1 },
    elbow: { char: 'マ', meaning: 'elbow', tier: 1 },
    heart: { char: '心', meaning: 'heart / mind', tier: 3 },
    legs: { char: '儿', meaning: 'legs', tier: 1 },
    fu: { char: 'フ', meaning: 'fu', tier: 1 },
    mountain: { char: '山', meaning: 'mountain', tier: 2 },
    ten: { char: '十', meaning: 'ten (cross)', tier: 1 },
    complete: { char: '了', meaning: 'complete', tier: 1 },
    fire: { char: '火', meaning: 'fire', tier: 3 },
    big: { char: '大', meaning: 'big', tier: 3 },
    plum: { char: '李', meaning: 'japanese plum', tier: 1 },
    honor: { char: '申', meaning: 'have the honor', tier: 1 },
    character: { char: '字', meaning: 'character', tier: 1 },
    rock: { char: '岩', meaning: 'rock', tier: 1 },
    mouth: { char: '口', meaning: 'mouth', tier: 2 },
    crown: { char: '宀', meaning: 'crown / roof', tier: 2 },
    earth: { char: '土', meaning: 'earth / soil', tier: 2 },
    stride: { char: '廴', meaning: 'stride/long stretch', tier: 2 },
    stone: { char: '石', meaning: 'stone', tier: 2 },
    three: { char: '三', meaning: 'three', tier: 2 },
    water: { char: '水', meaning: 'water', tier: 2 },
    small: { char: '小', meaning: 'small', tier: 2 },
    sun: { char: '日', meaning: 'sun / day', tier: 2 },
    woman: { char: '女', meaning: 'woman', tier: 2 },
    claw: { char: '⺤', meaning: 'claw', tier: 2 },
    child: { char: '子', meaning: 'child', tier: 2 },
    axe: { char: '斤', meaning: 'axe', tier: 2 },
    tree: { char: '木', meaning: 'tree', tier: 2 },
    again: { char: '又', meaning: 'again/grasp', tier: 2 },
    heaven: { char: '天', meaning: 'heaven', tier: 2 },
    middle: { char: '中', meaning: 'middle / inside', tier: 2 },
    dog: { char: '犬', meaning: 'dog', tier: 2 },
    peak: { char: '岳', meaning: 'peak', tier: 2 },
    everything: { char: '全', meaning: 'everything / all', tier: 2 },
    study: { char: '学', meaning: 'study / learning', tier: 2 },
    twenty: { char: '廾', meaning: 'twenty', tier: 2 },
    linger: { char: '彳', meaning: 'step', tier: 2 },
    dry: { char: '干', meaning: 'dry', tier: 2 },
    thousand: { char: '千', meaning: 'thousand', tier: 2 },
    seven: { char: '七', meaning: 'seven', tier: 1 },
    nine: { char: '九', meaning: 'nine', tier: 1 },
    knife: { char: '刀', meaning: 'knife / sword', tier: 1 },
    blade: { char: '刂', meaning: 'blade / side knife', tier: 1 },
    enter: { char: '入', meaning: 'enter', tier: 1 },
    power: { char: '力', meaning: 'power / strength', tier: 1 },
    yu: { char: 'ユ', meaning: 'katakana yu', tier: 1 },
    above: { char: '上', meaning: 'above / up', tier: 2 },
    below: { char: '下', meaning: 'below / down', tier: 2 },
    river: { char: '川', meaning: 'river', tier: 2 },
    craft: { char: '工', meaning: 'craft / work', tier: 2 },
    bow: { char: '弓', meaning: 'bow', tier: 2 },
    snake: { char: '己', meaning: 'snake / oneself', tier: 2 },
    evening: { char: '夕', meaning: 'evening', tier: 2 },
    five: { char: '五', meaning: 'five', tier: 3 },
    origin: { char: '元', meaning: 'origin', tier: 3 },
    villain: { char: '凶', meaning: 'villain', tier: 3 },
    slope: { char: '勾', meaning: 'slope', tier: 3 },
    inside: { char: '内', meaning: 'inside', tier: 3 },
    cut: { char: '切', meaning: 'cut', tier: 3 },
    public: { char: '公', meaning: 'public', tier: 3 },
    husband: { char: '夫', meaning: 'husband', tier: 3 },
    thick: { char: '太', meaning: 'thick / too much', tier: 3 },
    few: { char: '少', meaning: 'few / less', tier: 3 },
    door: { char: '戸', meaning: 'door / household', tier: 3 },
    friend: { char: '友', meaning: 'friend', tier: 3 },
    compare: { char: '比', meaning: 'compare', tier: 3 },
    four: { char: '四', meaning: 'four', tier: 4 },
    salute: { char: '礼', meaning: 'salute', tier: 4 },
    past: { char: '去 ', meaning: 'past', tier: 4 },
    history: { char: '史', meaning: 'history', tier: 4 },
    righteous: { char: '正', meaning: 'righteous / proper', tier: 4 },
    life: { char: '生', meaning: 'birth / life', tier: 4 },
    use: { char: '用', meaning: 'use', tier: 4 },
    stand: { char: '立', meaning: 'stand', tier: 4 },
    father: { char: '父', meaning: 'father', tier: 4 },
    half: { char: '半', meaning: 'half', tier: 4 },
    north: { char: '北', meaning: 'north', tier: 4 },
    citymarket: { char: '市', meaning: 'market / city', tier: 4 },
    outside: { char: '外', meaning: 'outside', tier: 4 },
    winter: { char: '冬', meaning: 'winter', tier: 4 },
    mother: { char: '母', meaning: 'mother', tier: 4 },
    make: { char: '乍', meaning: 'make', tier: 4 },
    fortuneteller: { char: '占', meaning: 'fortuneteller', tier: 4 },
    insect: { char: '虫', meaning: 'insect / bug', tier: 5 },
    times: { char: '回', meaning: 'times', tier: 5 },
    previous: { char: '先', meaning: 'previous', tier: 5 },
    punish: { char: '刑', meaning: 'punish', tier: 5 },
    officer: { char: '吏', meaning: 'officer', tier: 5 },
    colorhue: { char: '色', meaning: 'color / hue', tier: 5 },
    meat: { char: '肉', meaning: 'meat / flesh', tier: 5 },
    pighead: { char: '彐', meaning: 'pig head', tier: 2 },
    rice: { char: '米', meaning: 'rice', tier: 5 },
    goback: { char: '帰', meaning: 'return / go home', tier: 5 },
    clothing: { char: '衣', meaning: 'clothing', tier: 5 },
    body: { char: '体', meaning: 'body', tier: 6 },
    oldbird: { char: '隹', meaning: 'old bird', tier: 6 },
    soldier: { char: '兵', meaning: 'soldier / troops', tier: 6 },
    town: { char: '村', meaning: 'town', tier: 6 },
    walk: { char: '歩', meaning: 'walk', tier: 6 },
    every: { char: '毎', meaning: 'every / each', tier: 6 },
    what: { char: '何', meaning: 'what', tier: 6 },
    run: { char: '走', meaning: 'run', tier: 6 },
    long: { char: '長', meaning: 'long / leader', tier: 7 },
    elife: { char: '命', meaning: 'long life/ fate', tier: 7 },
    law: { char: '法', meaning: 'law', tier: 7 },
    sjewel: { char: '圭', meaning: 'jade / square jewel', tier: 7 },
    reality: { char: '実', meaning: 'reality / truth', tier: 7 },
    happy: { char: '幸', meaning: 'happiness / good fortune', tier: 7 },
    east: { char: '東', meaning: 'east', tier: 7 },
    night: { char: '夜', meaning: 'night', tier: 7 },
    straight: { char: '直', meaning: 'straight / direct', tier: 7 },
    shop: { char: '店', meaning: 'shop / store', tier: 7 },
    place: { char: '所', meaning: 'place / location', tier: 7 },
    begin: { char: '始', meaning: 'begin / start', tier: 7 },
    near: { char: '近', meaning: 'near / close', tier: 7 },
    south: { char: '南', meaning: 'south', tier: 8 },
    wash: { char: '洗', meaning: 'wash', tier: 8 },
    frame: { char: '架', meaning: 'frame', tier: 8 },
    cultivated: { char: '畑', meaning: 'cultivated field', tier: 8 },
    spring: { char: '春', meaning: 'spring (season)', tier: 8 },
    autumn: { char: '秋', meaning: 'autumn / fall', tier: 8 },
    wind: { char: '風', meaning: 'wind', tier: 8 },
    onfoot: { char: '徒', meaning: 'on foot / follow', tier: 9 },
    heavy: { char: '重', meaning: 'heavy', tier: 9 },
    horizon: { char: '涯', meaning: 'horizon', tier: 10 },
    impart: { char: '授', meaning: 'impart / give', tier: 10 },
    work: { char: '働', meaning: 'work', tier: 12 },
    separate: { char: '離', meaning: 'separate', tier: 15 },
    leap: { char: '躍', meaning: 'leap', tier: 20 },
    private: { char: '厶', meaning: 'private / myself', tier: 1 },
    seal: { char: '卩', meaning: 'seal', tier: 1 },
    bench: { char: '几', meaning: 'table / bench', tier: 1 },
    icedot: { char: '冫', meaning: 'ice / two-dot water', tier: 1 },
    mound: { char: '阝', meaning: 'village / mound', tier: 1 },
    me: { char: 'メ', meaning: 'katakana "me"', tier: 1 },
    gun: { char: '𠂉', meaning: 'gun', tier: 1 },
    shelter: { char: '广', meaning: 'shelter / lean-to', tier: 2 },
    measurement: { char: '寸', meaning: 'measurement / inch', tier: 2 },
    flag: { char: '尸', meaning: 'flag / roof radical', tier: 2 },
    shand: { char: '扌', meaning: 'side hand radical', tier: 2 },
    waterdot: { char: '氵', meaning: '3-dot water radical', tier: 2 },
    lgrass: { char: '艹', meaning: 'grass / plant radical', tier: 2 },
    feathers: { char: '彡', meaning: 'hair / feathers', tier: 2 },
    shoot: { char: '弋', meaning: 'shoot', tier: 2 },
    ke: { char: 'ケ', meaning: 'ke', tier: 2 },
    stop: { char: '止', meaning: 'stop / foot', tier: 3 },
    bfire: { char: '灬', meaning: 'fire / flames', tier: 3 },
    direction: { char: '方', meaning: 'direction / square', tier: 3 },
    lack: { char: '欠', meaning: 'lack / yawn', tier: 3 },
    writing: { char: '文', meaning: 'writing / sentence', tier: 3 },
    cow: { char: '牛', meaning: 'cow / ox', tier: 3 },
    fur: { char: '毛', meaning: 'hair / fur', tier: 3 },
    strike: { char: '攵', meaning: 'strike / tap', tier: 3 },
    steam: { char: '气', meaning: 'steam / air radical', tier: 3 },
    road: { char: '辶', meaning: 'walk / road radical', tier: 3 },
    altar: { char: 'ネ', meaning: 'altar / ne character', tier: 3 },
    tbranch: { char: '禾', meaning: '2 branch radical', tier: 4 },
    arrow: { char: '矢', meaning: 'arrow', tier: 4 },
    show: { char: '示', meaning: 'show / altar', tier: 4 },
    shortthread: { char: '幺', meaning: 'short thread', tier: 4 },
    thread: { char: '糸', meaning: 'thread / silk', tier: 5 },
    ear: { char: '耳', meaning: 'ear', tier: 5 },
    sheep: { char: '羊', meaning: 'sheep', tier: 5 },
    bamboo: { char: '竹', meaning: 'bamboo', tier: 5 },
    foot: { char: '足', meaning: 'foot / enough', tier: 6 },
    see: { char: '見', meaning: 'see / look', tier: 6 },
    village: { char: '里', meaning: 'village / ri unit', tier: 6 },
    rain: { char: '雨', meaning: 'rain', tier: 7 },
    blue: { char: '青', meaning: 'blue / young', tier: 7 },
    tsmall: { char: '⺍', meaning: 'small (top)', tier: 3 },
    six: { char: '六', meaning: 'six', tier: 3 },
    ice: { char: '氷', meaning: 'ice', tier: 3 },
    book: { char: '本', meaning: 'book/origin', tier: 3 },
    goods: { char: '品', meaning: 'goods / quality', tier: 3 },
    meet: { char: '合', meaning: 'meet / fit', tier: 3 },
    rest: { char: '休', meaning: 'rest', tier: 3 },
    dawn: { char: '旦', meaning: 'dawn', tier: 3 },
    hand: { char: '手', meaning: 'hand', tier: 3 },
    king: { char: '王', meaning: 'king', tier: 3 },
    field: { char: '田', meaning: 'rice field', tier: 3 },
    flame: { char: '炎', meaning: 'flame', tier: 3 },
    moon: { char: '月', meaning: 'moon / month', tier: 3 },
    yet: { char: '末', meaning: 'yet / still', tier: 3 },
    white: { char: '白', meaning: 'white', tier: 3 },
    eye: { char: '目', meaning: 'eye', tier: 4 },
    say: { char: '言', meaning: 'say / words', tier: 4 },
    lord: { char: '主', meaning: 'lord / master', tier: 4 },
    old: { char: '古', meaning: 'old', tier: 4 },
    obrother: { char: '兄', meaning: 'older brother', tier: 4 },
    safety: { char: '安', meaning: 'safety / peace', tier: 4 },
    guy: { char: '奴', meaning: 'guy / slave', tier: 4 },
    jewel: { char: '玉', meaning: 'jewel', tier: 4 },
    hole: { char: '穴', meaning: 'hole', tier: 4 },
    branch: { char: '支', meaning: 'branch', tier: 4 },
    self: { char: '自', meaning: 'self', tier: 5 },
    together: { char: '共', meaning: 'together', tier: 5 },
    accept: { char: '受', meaning: 'accept', tier: 5 },
    think: { char: '思', meaning: 'think', tier: 5 },
    gold: { char: '金', meaning: 'gold / metal', tier: 5 },
    blaze: { char: '焱', meaning: 'blaze (three fires)', tier: 5 },
    tongue: { char: '舌', meaning: 'tongue', tier: 5 },
    likeable: { char: '好', meaning: 'likeable', tier: 5 },
    ysister: { char: '妹', meaning: 'younger sister', tier: 5 },
    car: { char: '車', meaning: 'car', tier: 5 },
    grove: { char: '林', meaning: 'grove', tier: 5 },
    country: { char: '国', meaning: 'country', tier: 6 },
    bright: { char: '明', meaning: 'bright', tier: 6 },
    riot: { char: '乱', meaning: 'riot / disturbance', tier: 6 },
    overcome: { char: '克', meaning: 'overcome', tier: 6 },
    angry: { char: '怒', meaning: 'anger', tier: 6 },
    skin: { char: '皮', meaning: 'skin', tier: 6 },
    spicy: { char: '辛', meaning: 'spicy', tier: 6 },
    love: { char: '愛', meaning: 'love', tier: 7 },
    gate: { char: '門', meaning: 'gate', tier: 7 },
    messenger: { char: '使', meaning: 'send/serve', tier: 7 },
    morning: { char: '朝', meaning: 'morning', tier: 8 },
    fruit: { char: '果', meaning: 'fruit', tier: 8 },
    interval: { char: '間', meaning: 'interval', tier: 8 },
    forest: { char: '森', meaning: 'forest', tier: 8 },
    talk: { char: '話', meaning: 'talk / story', tier: 8 },
    between: { char: '間', meaning: 'between / interval', tier: 8 },
    him: { char: '彼', meaning: 'him', tier: 8 },
    finger: { char: '指', meaning: 'finger', tier: 8 },
    parent: { char: '親', meaning: 'parent', tier: 12 },
};

// Merge recipes — stored as objects (Firestore does not support arrays of arrays)
const RAW_MERGES = [
    ['cstroke', 'gun', '', '', 'cliff', 30],
    ['cliff', 'dot', '', '', 'shelter', 60],
    ['shelter', 'divining', 'mouth', '', 'store', 300],
    ['shelter', 'dot', '', '', 'na', 70],
    ['ten', 'cstroke', '', '', 'na', 70],
    ['na', 'again', '', '', 'friend', 200],
    ['na', 'yu', '', '', 'five', 300],
    ['cliff', 'benthook', '', '', 'table', 60],
    ['cliff', 'hline', '', '', 'sbox', 60],
    ['sbox', 'vline', '', '', 'mouth', 60],
    ['hline', 'hook', '', '', 'street', 30],
    ['street', 'wrap', '', '', 'bow', 70],
    ['street', 'dot', '', '', 'measurement', 150],
    ['hline', 'hook', 'dot', '', 'measurement', 150],
    ['measurement', 'tree', '', '', 'town', 500],
    ['hline', 'hook', 'cstroke', '', 'shand', 60],
    ['hline', 'benthook', '', '', 'rbend', 60],
    ['rbend', 'cstroke', '', '', 'nine', 100],
    ['hline', 'hline', '', '', 'two', 30],
    ['hline', 'vline', '', '', 'ten', 30],
    ['hline', 'cstroke', '', '', 'fu', 30],
    ['hline', 'dot', '', '', 'lid', 30],
    ['hline', 'dot', 'dot', '', 'cover', 30],
    ['fu', 'fu', 'bend', '', 'stride', 60],
    ['stride', 'dot', 'dot', '', 'road', 60],
    ['hline', 'vline', 'hook', '', 'dbox', 60],
    ['dbox', 'street', 'grass', 'grass', 'rain', 3000],
    ['dbox', 'lid', 'vline', '', 'citymarket', 200],
    ['dbox', 'ten', '', '', 'citymarket', 200],
    ['dbox', 'vline', '', '', 'seal', 60],
    ['citymarket', 'pighead', 'blade', '', 'goback', 1500],
    ['hline', 'person', '', '', 'big', 100],
    ['hline', 'cstroke', 'benthook', '', 'big', 100],
    ['big', 'dot', '', '', 'dog', 120],
    ['big', 'gun', '', '', 'arrow', 120],
    ['big', 'lid', '', '', 'husband', 500],
    ['big', 'private', '', '', 'clothing', 500],
    ['clothing', 'three', 'hline', '', 'long', 600],
    ['gun', 'hline', 'bend', '', 'steam', 120],
    ['gun', 'ten', '', '', 'cow', 120],
    ['gun', 'me', '', '', 'strike', 120],
    ['strike', 'dot', 'lid', 'person', 'night', 700],
    ['strike', 'two', '', '', 'winter', 200],
    ['gun', 'vline', '', '', 'ke', 60],
    ['gun', 'hook', '', '', 'wrap', 70],
    ['gun', 'vline', 'two', '', 'make', 200],
    ['ke', 'two', '', '', 'make', 200],
    ['gun', 'gun', 'dbox', '', 'bamboo', 250],
    ['hline', 'hline', 'hline', '', 'three', 100],
    ['hline', 'vline', 'vline', '', 'container', 100],
    ['vline', 'vline', 'vline', '', 'river', 80],
    ['hline', 'tree', '', '', 'book', 150],
    ['book', 'person', '', '', 'body', 600],
    ['hline', 'earth', '', '', 'king', 150],
    ['three', 'vline', '', '', 'king', 150],
    ['king', 'moon', '', '', 'blue', 300],
    ['king', 'grass', '', '', 'sheep', 300],
    ['king', 'vline', 'vline', '', 'field', 300],
    ['king', 'eight', 'sun', '', 'spring', 500],
    ['king', 'person', 'crown', '', 'reality', 500],
    ['king', 'tperson', 'vline', 'dot', 'oldbird', 500],
    ['make', 'hline', 'vline', 'dot', 'oldbird', 500],
    ['hline', 'big', '', '', 'heaven', 80],
    ['heaven', 'dot', '', '', 'arrow', 100],
    ['hline', 'tsmall', '', '', 'claw', 60],
    ['rbend', 'dot', '', '', 'shoot', 60],
    ['hline', 'benthook', 'dot', '', 'shoot', 60],
    ['fu', 'benthook', '', '', 'again', 80],
    ['fu', 'hook', '', '', 'complete', 30],
    ['fu', 'bend', '', '', 'woman', 60],
    ['fu', 'vline', 'bend', '', 'mound', 80],
    ['fu', 'hline', '', '', 'yu', 80],
    ['fu', 'dot', '', '', 'elbow', 60],
    ['elbow', 'divining', '', '', 'altar', 100],
    ['fu', 'dot', 'divining', '', 'altar', 100],
    ['altar', 'benthook', '', '', 'salute', 500],
    ['fu', 'dot', 'cstroke', '', 'evening', 100],
    ['ke', 'ke', '', '', 'bamboo', 300],
    ['branch', 'cliff', '', '', 'skin', 1000],
    ['skin', 'linger', '', '', 'him', 2000],
    ['cover', 'dot', '', '', 'crown', 60],
    ['crown', 'eight', '', '', 'hole', 200],
    ['cstroke', 'cstroke', '', '', 'eight', 30],
    ['cstroke', 'cstroke', 'cstroke', '', 'feathers', 50],
    ['cstroke', 'vline', '', '', 'tperson', 30],
    ['cstroke', 'benthook', '', '', 'person', 30],
    ['cstroke', 'dot', 'dot', '', 'waterdot', 60],
    ['cstroke', 'bend', '', '', 'me', 30],
    ['me', 'container', '', '', 'villain', 30],
    ['villain', 'lid', 'slope', 'oldbird', 'separate', 3000],
    ['me', 'bend', '', '', 'me', 30],
    ['dot', 'hook', '', '', 'spoon', 70],
    ['bend', 'bend', '', '', 'snake', 100],
    ['spoon', 'shand', '', '', 'north', 110],
    ['spoon', 'sun', 'shand', '', 'finger', 150],
    ['spoon', 'above', '', '', 'compare', 250],
    ['spoon', 'knife', '', '', 'cut', 250],
    ['spoon', 'dot', '', '', 'seven', 250],
    ['cstroke', 'dot', '', '', 'icedot', 30],
    ['icedot', 'dot', '', '', 'waterdot', 40],
    ['cstroke', 'wrap', '', '', 'power', 30],
    ['cstroke', 'street', '', '', 'knife', 100],
    ['knife', 'dot', '', '', 'power', 100],
    ['cstroke', 'street', 'lid', '', 'direction', 150],
    ['knife', 'lid', '', '', 'direction', 150],
    ['cstroke', 'fu', '', '', 'wrap', 70],
    ['cstroke', 'dot', 'cstroke', '', 'wrap', 70],
    ['wrap', 'dot', '', '', 'evening', 70],
    ['evening', 'bend', 'person', 'lid', 'night', 700],
    ['evening', 'diviner', '', '', 'outside', 100],
    ['wrap', 'middle', 'bend', '', 'colorhue', 250],
    ['tperson', 'cstroke', '', '', 'linger', 100],
    ['tperson', 'king', 'lid', '', 'oldbird', 400],
    ['old', 'cstroke', '', '', 'tongue', 400],
    ['person', 'dot', 'dot', '', 'fire', 300],
    ['person', 'dot', 'lid', '', 'thick', 500],
    ['person', 'grass', '', '', 'fire', 300],
    ['person', 'dot', 'mouth', 'seal', 'elife', 1000],
    ['person', 'tree', '', '', 'rest', 100],
    ['rest', 'hline', '', '', 'body', 600],
    ['person', 'king', '', '', 'everything', 100],
    ['person', 'street', 'mouth', '', 'what', 300],
    ['person', 'dbox', '', '', 'inside', 100],
    ['inside', 'person', '', '', 'meat', 200],
    ['person', 'dot', 'gun', '', 'lack', 200],
    ['person', 'dot', '', '', 'enter', 200],
    ['dot', 'dot', '', '', 'grass', 30],
    ['grass', 'dot', '', '', 'tsmall', 50],
    ['grass', 'hline', '', '', 'lgrass', 60],
    ['grass', 'grass', '', '', 'bfire', 100],
    ['dot', 'dot', 'dot', '', 'tsmall', 60],
    ['lid', 'king', '', '', 'lord', 250],
    ['lord', 'tperson', '', '', 'oldbird', 500],
    ['dot', 'eye', '', '', 'self', 300],
    ['self', 'sbox', '', '', 'straight', 400],
    ['dot', 'eye', 'sbox', '', 'straight', 400],
    ['dot', 'street', '', '', 'ke', 60],
    ['dot', 'vline', '', '', 'divining', 60],
    ['divining', 'mouth', '', '', 'fortuneteller', 150],
    ['fortuneteller', 'shelter', '', '', 'store', 250],
    ['divining', 'stride', 'mouth', '', 'foot', 300],
    ['foot', 'pighead', 'pighead', 'oldbird', 'leap', 1500],
    ['divining', 'hline', '', '', 'above', 80],
    ['above', 'hline', '', '', 'craft', 80],
    ['above', 'vline', '', '', 'stop', 100],
    ['stop', 'few', '', '', 'walk', 400],
    ['stop', 'hline', '', '', 'righteous', 200],
    ['righteous', 'ten', 'stride', '', 'run', 1500],
    ['container', 'vline', '', '', 'mountain', 30],
    ['container', 'hline', '', '', 'mouth', 80],
    ['mouth', 'hline', '', '', 'sun', 70],
    ['mouth', 'mouth', '', '', 'times', 100],
    ['times', 'legs', '', '', 'four', 300],
    ['mouth', 'mouth', 'mouth', '', 'goods', 200],
    ['mouth', 'vline', '', '', 'middle', 70],
    ['middle', 'private', '', '', 'bug', 150],
    ['middle', 'stride', '', '', 'history', 200],
    ['history', 'lid', '', '', 'officer', 400],
    ['tperson', 'mouth', 'na', 'stride', 'messenger', 1000],
    ['officer', 'tperson', '', '', 'messenger', 1000],
    ['bug', 'hline', 'table', '', 'wind', 350],
    ['mouth', 'person', 'hline', '', 'meet', 250],
    ['meet', 'seal', '', '', 'elife', 900],
    ['mouth', 'cstroke', '', '', 'flag', 250],
    ['flag', 'hline', '', '', 'door', 300],
    ['three', 'mouth', 'dot', '', 'say', 300],
    ['three', 'hook', '', '', 'hand', 150],
    ['hand', 'benthook', '', '', 'fur', 150],
    ['three', 'vline', 'grass', '', 'sheep', 150],
    ['three', 'vline', 'dot', 'dot', 'sheep', 150],
    ['legs', 'mouth', '', '', 'obrother', 300],
    ['ten', 'mouth', '', '', 'old', 300],
    ['gate', 'mouth', '', '', 'between', 2000],
    ['two', 'lid', 'mouth', '', 'say', 300],
    ['two', 'vline', 'vline', '', 'mouth', 80],
    ['two', 'cstroke', '', '', 'thousand', 60],
    ['two', 'vline', '', '', 'dry', 60],
    ['dry', 'tsmall', '', '', 'half', 150],
    ['dry', 'cstroke', '', '', 'below', 150],
    ['dry', 'dot', '', '', 'cow', 100],
    ['cow', 'hline', '', '', 'life', 300],
    ['two', 'vline', 'dot', '', 'cow', 100],
    ['two', 'hline', '', '', 'three', 60],
    ['two', 'person', 'dot', '', 'arrow', 200],
    ['two', 'small', '', '', 'show', 100],
    ['two', 'legs', '', '', 'origin', 300],
    ['origin', 'ke', '', '', 'previous', 700],
    ['previous', 'waterdot', '', '', 'wash', 700],
    ['eight', 'hook', '', '', 'small', 60],
    ['grass', 'hook', '', '', 'small', 60],
    ['dot', 'hook', 'dot', '', 'small', 60],
    ['small', 'cstroke', '', '', 'few', 80],
    ['dot', 'king', '', '', 'jewel', 250],
    ['eight', 'me', '', '', 'father', 250],
    ['lid', 'eight', '', '', 'six', 100],
    ['six', 'hline', '', '', 'stand', 200],
    ['lid', 'hline', 'grass', '', 'stand', 200],
    ['lid', 'container', '', '', 'stand', 200],
    ['stand', 'ten', '', '', 'spicy', 400],
    ['dry', 'grass', 'lid', '', 'spicy', 400],
    ['spicy', 'lid', '', '', 'happy', 200],
    ['spicy', 'dbox', '', '', 'south', 300],
    ['stand', 'tree', 'see', '', 'parent', 4000],
    ['ten', 'hline', '', '', 'earth', 60],
    ['earth', 'stop', '', '', 'run', 120],
    ['earth', 'earth', '', '', 'sjewel', 500],
    ['earth', 'private', '', '', 'past', 500],
    ['earth', 'dot', 'legs', '', 'previous', 700],
    ['past', 'waterdot', '', '', 'law', 1000],
    ['sjewel', 'cliff', 'waterdot', '', 'horizon', 800],
    ['run', 'linger', '', '', 'onfoot', 1000],
    ['ten', 'person', '', '', 'tree', 60],
    ['ten', 'ten', '', '', 'twenty', 100],
    ['twenty', 'hline', 'blade', '', 'punish', 1000],
    ['tperson', 'na', 'mouth', 'bend', 'messenger', 1000],
    ['complete', 'hline', '', '', 'child', 60],
    ['cliff', 'ten', '', '', 'axe', 80],
    ['axe', 'eight', '', '', 'soldier', 100],
    ['axe', 'mountain', '', '', 'peak', 100],
    ['axe', 'door', '', '', 'place', 100],
    ['axe', 'road', '', '', 'near', 200],
    ['child', 'tree', '', '', 'plum', 30],
    ['child', 'crown', '', '', 'character', 200],
    ['character', 'tsmall', '', '', 'study', 300],
    ['woman', 'crown', '', '', 'safety', 300],
    ['woman', 'again', '', '', 'guy', 300],
    ['woman', 'child', '', '', 'likeable', 400],
    ['woman', 'yet', '', '', 'ysister', 500],
    ['woman', 'ten', '', '', 'ysister', 500],
    ['woman', 'waterdot', '', '', 'mother', 500],
    ['woman', 'private', 'mouth', '', 'begin', 500],
    ['mother', 'gun', '', '', 'every', 600],
    ['sun', 'hline', '', '', 'dawn', 60],
    ['sun', 'vline', '', '', 'field', 60],
    ['field', 'earth', '', '', 'village', 600],
    ['field', 'heart', '', '', 'think', 2000],
    ['field', 'fire', '', '', 'cultivated', 1000],
    ['field', 'two', '', '', 'car', 700],
    ['field', 'tree', '', '', 'fruit', 900],
    ['field', 'small', '', '', 'use', 1000],
    ['car', 'two', '', '', 'heavy', 900],
    ['heavy', 'tperson', 'power', '', 'work', 2000],
    ['field', 'ten', 'person', 'vline', 'east', 800],
    ['sun', 'dbox', '', '', 'moon', 200],
    ['moon', 'moon', '', '', 'use', 1000],
    ['sun', 'dot', '', '', 'white', 200],
    ['sun', 'moon', '', '', 'bright', 450],
    ['sun', 'sun', 'blade', '', 'gate', 450],
    ['sun', 'container', '', '', 'eye', 200],
    ['eye', 'legs', '', '', 'see', 500],
    ['eye', 'shoot', '', '', 'ear', 500],
    ['hook', 'fu', 'lid', '', 'water', 70],
    ['water', 'dot', '', '', 'ice', 700],
    ['hook', 'vline', '', '', 'blade', 70],
    ['blade', 'cstroke', '', '', 'knife', 100],
    ['hook', 'benthook', '', '', 'legs', 30],
    ['benthook', 'tsmall', '', '', 'heart', 200],
    ['benthook', 'dot', 'dot', 'dot', 'heart', 200],
    ['bend', 'dot', '', '', 'private', 200],
    ['private', 'wrap', '', '', 'slope', 300],
    ['private', 'eight', '', '', 'public', 500],
    ['private', 'private', '', '', 'shortthread', 200],
    ['shortthread', 'small', '', '', 'thread', 500],
    ['guy', 'heart', '', '', 'angry', 500],
    ['heart', 'accept', '', '', 'love', 1000],
    ['heart', 'cover', 'claw', 'strike', 'love', 1000],
    ['mountain', 'stone', '', '', 'rock', 300],
    ['tree', 'lid', '', '', 'yet', 200],
    ['tree', 'power', 'mouth', '', 'fram', 1000],
    ['tree', 'cstroke', '', '', 'tbranch', 200],
    ['tbranch', 'fire', '', '', 'autumn', 250],
    ['tree', 'grass', '', '', 'rice', 220],
    ['tree', 'tree', '', '', 'grove', 400],
    ['grove', 'tree', '', '', 'forest', 2000],
    ['fire', 'fire', '', '', 'flame', 900],
    ['flame', 'fire', '', '', 'blaze', 1200],
    ['again', 'ten', '', '', 'branch', 200],
    ['again', 'claw', 'cover', '', 'accept', 500],
    ['accept', 'shand', '', '', 'impart', 800],
    ['again', 'cstroke', '', '', 'strike', 400],
    ['again', 'lid', '', '', 'writing', 400],
    ['king', 'person', 'eight', '', 'gold', 400],
    ['tongue', 'bend', '', '', 'riot', 500],
    ['old', 'legs', '', '', 'overcome', 500],
    ['bright', 'sun', '', '', 'interval', 1000],
    ['together', 'person', '', '', 'submit', 1000],
    ['car', 'moon', '', '', 'morning', 2000],
    ['say', 'tongue', '', '', 'talk', 2000],
];

// ─── Build Firestore payload ──────────────────────────────────────────────────

const tilesPayload = {};
for (const [id, t] of Object.entries(RAW_TILES)) {
    tilesPayload[id] = { char: t.char, meaning: t.meaning, tier: t.tier };
}

const mergesPayload = RAW_MERGES.map(([a, b, c, d, result, xp]) => ({
    a: String(a), b: String(b), c: String(c), d: String(d),
    result: String(result), xp: Number(xp),
}));

const gameData = {
    tiles: tilesPayload,
    merges: mergesPayload,
    targetPool: TARGET_POOL,
};

// ─── Write ────────────────────────────────────────────────────────────────────

async function main() {
    console.log(`📦 Tiles: ${Object.keys(tilesPayload).length}`);
    console.log(`🔀 Merges: ${mergesPayload.length}`);
    console.log(`🎯 Target pool: ${TARGET_POOL.length}`);

    if (DRY) {
        console.log('\n✅ Dry-run complete — no writes performed.');
        process.exit(0);
    }

    try {
        await db.collection('kanjiDrop').doc('gameData').set(gameData);
        console.log('\n✅ Successfully wrote kanjiDrop/gameData to Firestore.');
    } catch (err) {
        console.error('❌ Error writing to Firestore:', err);
        process.exit(1);
    }
    process.exit(0);
}

main();
